language: cpp
compiler:
 - gcc
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script: 
  - mkdir build
  - cd build
  - CC=gcc-7 CXX=g++-7 cmake ..
  - make -j4
