language: cpp
compiler:
 - gcc
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libarmadillo-dev
script: 
  - cmake --version
  - mkdir build
  - cd build
  - CC=gcc-8 CXX=g++-8 cmake ..
  - make -j4
